# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

In [103]:
import pandas as pd

In [104]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance_df = pd.read_csv(url)
insurance_df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [105]:
insurance_df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [106]:
# Your code here
insurance_df = insurance_df.rename(
    columns={
        "Customer": "customer",
        "ST": "state",
        "GENDER": "gender",
        "Education": "education",
        "Customer Lifetime Value": "customer_lifetime_value",
        "Income": "income",
        "Monthly Premium Auto": "monthly_premium_auto",
        "Number of Open Complaints": "number_of_open_complaints",
        "Policy Type": "policy_type",
        "Vehicle Class": "vehicle_class",
        "Total Claim Amount": "total_claim_amount",
    }
)

insurance_df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [107]:
# Your code here
# Gender column
insurance_df["gender"].unique()

<ArrowStringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str

In [108]:
# State column
insurance_df["state"].unique()

<ArrowStringArray>
['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       'Cali',         'AZ',         'WA',          nan]
Length: 9, dtype: str

In [109]:
# Education
insurance_df["education"].unique()

<ArrowStringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str

In [110]:
# customer_lifetime_value column
insurance_df["customer_lifetime_value"].unique()

<ArrowStringArray>
[          nan,  '697953.59%', '1288743.17%',  '764586.18%',  '536307.65%',
  '825629.78%',  '538089.86%',  '721610.03%', '2412750.40%',  '738817.81%',
 ...
  '943891.56%', '1050677.17%',  '421391.86%',  '477368.64%',  '544142.01%',
  '284226.69%',  '305955.03%', '2031499.76%',  '323912.47%',  '899704.02%']
Length: 1028, dtype: str

In [111]:
# vehicle_class column
insurance_df["vehicle_class"].unique()

<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str

In [112]:
# Replace inconsistent gender values
insurance_df["gender"] = insurance_df["gender"].replace(
    {"Femal": "F", "female": "F", "Male": "M"}
)

# Replace inconsistent state values
insurance_df["state"] = insurance_df["state"].replace(
    {"Cali": "California", "WA": "Washington", "AZ": "Arizona"}
)

# Replace inconsistent education values
insurance_df["education"] = insurance_df["education"].replace({"Bachelors": "Bachelor"})

# Remove % character from customer_lifetime_value
insurance_df["customer_lifetime_value"] = insurance_df[
    "customer_lifetime_value"
].str.replace("%", "")

# Replace inconsistent vehicle_class values
insurance_df["vehicle_class"] = insurance_df["vehicle_class"].replace(
    {"Sports Car": "Luxury", "Luxury Car": "Luxury", "Luxury SUV": "Luxury"}
)

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [113]:
# Your code here
insurance_df["customer_lifetime_value"].dtype

In [114]:
# Convert customer lifetime value from string to float
insurance_df["customer_lifetime_value"] = pd.to_numeric(
    insurance_df["customer_lifetime_value"]
)

In [115]:
insurance_df["number_of_open_complaints"].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [116]:
# Extract the middle number from the "number_of_open_complaints" values and keep NaN values unchanged
insurance_df["number_of_open_complaints"] = insurance_df[
    "number_of_open_complaints"
].apply(
    lambda middle_num: (
        middle_num.split("/")[1] if not pd.isna(middle_num) else middle_num
    )
)

In [117]:
# Convert number of open complaints from string to numeric
insurance_df["number_of_open_complaints"] = pd.to_numeric(
    insurance_df["number_of_open_complaints"]
)

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [120]:
# Your code here
# Check how many missing values we have in each column
insurance_df.isnull().sum()

customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [119]:
# Remove rows where all values are missing
insurance_df = insurance_df.dropna(how="all")

In [ ]:
# Find the most common gender
insurance_df["gender"].mode()

# Fill missing gender values with the most common gender
insurance_df["gender"] = insurance_df["gender"].fillna(insurance_df["gender"].mode()[0])

In [ ]:
# Find the median customer lifetime value
insurance_df["customer_lifetime_value"].median()

# Fill missing customer lifetime values with the median
insurance_df["customer_lifetime_value"] = insurance_df[
    "customer_lifetime_value"
].fillna(insurance_df["customer_lifetime_value"].median())

# Check if there are any missing values left
insurance_df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [132]:
# Your code here
# Check how many duplicate rows we have
insurance_df.duplicated().sum()

np.int64(0)

In [133]:
# Remove duplicate rows
insurance_df = insurance_df.drop_duplicates()


# Reset the index after checking/removing duplicates
insurance_df = insurance_df.reset_index(drop=True)


# Check again that there are no duplicate rows
insurance_df.duplicated().sum()


# Save the cleaned dataframe as a CSV file
insurance_df.to_csv("insurance_cleaned.csv", index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here